apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: base-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: base-vm
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 2Gi
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
              bootOrder: 2
            - name: cloudinitdisk
              disk:
                bus: virtio
      volumes:
        - name: rootdisk
          dataVolume:
            name: base-vm-disk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: base-vm
              users:
                - name: cloud
                  groups: wheel, sudo
                  ssh-authorized-keys:
                    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCcZbdLr0badPq6RF1yHo2DkfbXfftVP4FwqJ1ees68DYWXEsxqzjAiQQtwmgter4txmNvlSNgNuhRc4bnLPMZHR/zOnGihc/kSoLFGis7u1vukCOQDa34Xc+VwBIEDVRSz0ImFRS2bBE/bzHaxmRTQUcrP3gH53mB48nRAKl51baOZT9b3wmnzbLgK0Uoef9LouRtJIE9IR8fnfk268onF9UCS8qbfTnsRiTKZJbW5ne2xzSpj2YH6+UEtJlWimOTLF2nMY0acuvuS1mOyLUiouI0LLR3PZyFPecibu0tgdlT+jQIU0EGGfJE8pL8EZCB+E4AVUbCnBZY2G3tZ1l/UcFGdoZLjBfaxOawincccQTu4CfmZnwsomO6kRiUTqyckTd3IRuDTqJS71hB66ToUuJNiwPid+/XTwc2MY1FMI8HFD5ch9PYCmxt3uJplZp0GuFrhNZNAkPdRmHfbRlZAO9nwXv0aGdCotSrA71L+d7fCNo3UkF5jggm39XN+910=
                  password: redhat
                  lock_passwd: false
                  chpasswd: { expire: False }
              runcmd:
                - echo "Cloud-init finished."
              user: cloud
              password: redhat

