apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: base-vm-disk
spec:
  source:
    registry:
      url: "docker://registry.redhat.io/rhel8/rhel-guest-image:latest"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
    storageClassName: ocs-storagecluster-ceph-rbd-virtualization

