apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: base-vm-disk
spec:
  source:
    blank: {}
  pvc:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 30Gi
    storageClassName: ocs-storagecluster-ceph-rbd-virtualization

