apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: base-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: base-vm
    spec:
      domain:
        cpu:
          cores: 2
        memory:
          guest: 2Gi
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
              bootOrder: 2
            - name: cloudinitdisk
              disk:
                bus: virtio
      volumes:
        - name: rootdisk
          dataVolume:
            name: base-vm-disk
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: large-script-secret
